### ISSUE TITLE
Failing to check for new files

### ISSUE THREAD

**Issue by MrDecepticon** [Womabre/unraid-docker-templates#15]
Recently my icloudPD installations have been failing the new file check.  I initially thought it was the MFA check but I ran the initialization script and re-authorized it.  Still fails with the following errors:

```2023-03-27 15:41:26 ERROR    Failed check for new files files
2023-03-27 15:41:26 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-03-27 15:41:26 ERROR    Error debugging info:
2023-03-27 15:41:26 ERROR    Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 288, in main
    core(
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 728, in core
    download_photo(consecutive_files_found, item)
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 361, in download_photo_
    created_date = photo.created.astimezone(get_localzone())
  File "/usr/lib/python3.10/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/lib/python3.10/site-packages/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/usr/lib/python3.10/site-packages/tzlocal/utils.py", line 125, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
2023-03-27 15:41:26 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-03-27 15:41:26 INFO     Sending Discord failure notification
2023-03-27 15:41:26 INFO     Discord failure notification sent successfully
2023-03-27 15:41:26 INFO     Web cookie expires: 2023-05-26 @ 12:07:10
2023-03-27 15:41:26 INFO     Two factor authentication cookie expires: 2023-06-25 @ 12:07:27
2023-03-27 15:41:26 INFO     Days remaining until expiration: 89
2023-03-27 15:41:26 INFO     iCloud login counter = 1
2023-03-27 15:41:26 INFO     Synchronisation ended at 15:41:26
2023-03-27 15:41:26 INFO     Total time taken: 00:00:15
2023-03-27 15:41:26 INFO     Next synchronisation at 15:41:11
```

According to my Unraid Docker manager there are no updates available.  There are no other popups on icloud.com other than the MFA check.

**Comment by MrDecepticon** [comment]
This seems to have been caused by an invalid Time Zone - which is odd since it has been set to America/New York since day one of install.  It is now just starting to complain about it.  Apparently the City requires the underscore between New and York.  Changing it to America/New_York resolved the issue for me.
