### ISSUE TITLE
Deleting and recreating the container causes authentication to fail

### ISSUE THREAD

**Issue by dlang123** [Womabre/unraid-docker-templates#17]
I had it working just fine, then I changed the folder structure from album to nothing to get y m d, and when the container restarted it said that authentication failed.  I deleted the container and tried to recreate it several times, and each time I get the following error:

```

 sync-icloud.sh --Initialise

2023-12-08 07:46:00 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.684 started *****
2023-12-08 07:46:00 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-12-08 07:46:00 INFO     Alpine Linux 3.18.3
2023-12-08 07:46:00 INFO     Python version: 3.11.5
2023-12-08 07:46:00 INFO     Loading configuration from: /config/icloudpd.conf
2023-12-08 07:46:06 INFO     Apple ID: xxxx
2023-12-08 07:46:06 INFO     Authentication Type: MFA
2023-12-08 07:46:06 INFO     Cookie path: /config/xxxx
2023-12-08 07:46:06 INFO     Cookie expiry notification period: 7
2023-12-08 07:46:06 INFO     Download destination directory: /home/user/iCloud
2023-12-08 07:46:06 INFO     Folder structure: {:%Y/%m/%d}
2023-12-08 07:46:06 INFO     Synchronisation interval: 86400
2023-12-08 07:46:06 INFO     Synchronisation delay (minutes): 5
2023-12-08 07:46:06 INFO     Set EXIF date/time: false
2023-12-08 07:46:06 INFO     Auto delete: false
2023-12-08 07:46:06 INFO     Delete after download: false
2023-12-08 07:46:06 INFO     Photo size: original
2023-12-08 07:46:06 INFO     Single pass mode: false
2023-12-08 07:46:06 INFO     Skip download check: false
2023-12-08 07:46:06 INFO     Skip live photos: false
2023-12-08 07:46:06 INFO     Number of most recently added photos to download: Download All Photos
2023-12-08 07:46:06 INFO     Downloading photos from: Download All Photos
2023-12-08 07:46:06 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-12-08 07:46:06 INFO     Live photo size: original
2023-12-08 07:46:07 INFO     Skip videos: false
2023-12-08 07:46:07 INFO     Convert HEIC to JPEG: true
2023-12-08 07:46:07 INFO     Downloading from: icloud.com
2023-12-08 07:46:07 INFO     Authentication domain: com
2023-12-08 07:46:07 INFO     Ignore Synology extended attribute directories: Disabled
2023-12-08 07:46:07 INFO     Script launch parameters: --Initialise
Enter iCloud password for : 
Bad username or password for xxxx
Enter iCloud password for xxxx: 
Bad username or password for xxxx
Enter iCloud password for xxxx: 
Traceback (most recent call last):
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
    req = self.session.post(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    api = pyicloud_ipd.PyiCloudService(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloud", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/cmdline.py", line 259, in main
    raise RuntimeError(message)
RuntimeError: Bad username or password for xxxx
2023-12-08 07:47:16 ERROR    Keyring file does not exist. Please try again.
```

I have changed the config path, the password is definitely correct, I can use it to login to the website.  Any idea?

**Comment by MrDecepticon** [comment]
I am having this same exact issue on two separate docker images/instances/installations.  I had a power failure about a week ago and have been having this exact log message in both ever since.  I have changed nothing about my icloud account and can log in to both accounts on apple's icloud website.  Running the --initialize switch does not fix it as it requests authentication and insists my password/username is incorrect. 

I even removed the keystore/keyring to rebuild but it won't even get to that point as it does not accept my credentials even though I know for a fact they are correct. 

```

2023-12-08 07:30:19 INFO     Synchronisation starting at 07:30:19
2023-12-08 07:30:19 INFO     Keyring file exists, continuing
2023-12-08 07:30:19 INFO     Check download directory mounted correctly...
2023-12-08 07:30:19 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-12-08 07:30:19 INFO     Check for new files using password stored in keyring file
2023-12-08 07:30:19 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023-12-08 07:30:20 ERROR    Unknown reason
2023-12-08 07:30:20 ERROR    Failed check for new files files
2023-12-08 07:30:20 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2023-12-08 07:30:20 ERROR    Error debugging info:
2023-12-08 07:30:20 ERROR    Traceback (most recent call last):
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
    req = self.session.post(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
    self._raise_error(code, reason)
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
    core(
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
    icloud = authenticator(logger, domain)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
    icloud = pyicloud_ipd.PyiCloudService(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
    self.authenticate()
  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2023-12-08 07:30:20 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-12-08 07:30:20 INFO     Sending Discord failure notification
2023-12-08 07:30:20 INFO     Web cookie expires: 2024-01-29 @ 20:16:59
2023-12-08 07:30:20 INFO     Multifactor authentication cookie expires: 2024-02-28 @ 20:17:13
2023-12-08 07:30:20 INFO     Days remaining until expiration: 82
2023-12-08 07:30:20 INFO     Synchronisation ended at 07:30:20
2023-12-08 07:30:20 INFO     Total time taken: 00:00:01
```

**Comment by MrDecepticon** [comment]
Just some more info:  I checked the app repository for icloudpd and noticed that it did not show that it was installed (acting as if I never installed it).  So, I removed my existing docker image and reinstalled.  This was definitely newer than my existing installation as there are WAY more options.  Added all the appropriate settings from my old installation and went to initialize.  I had to add the variable force_gid as it was throwing an error about group 100 already being in use.   Same issue.  It is not accepting my credentials at all:
```

2023-12-08 11:58:06 INFO     Sending Discord startup notification
2023-12-08 11:58:06 INFO     Downloading from: icloud.com
2023-12-08 11:58:06 INFO     Authentication domain: com
2023-12-08 11:58:06 INFO     Ignore Synology extended attribute directories: Disabled
2023-12-08 11:58:06 INFO     Script launch parameters: --initialise
2023-12-08 11:58:06 WARNING  Group id, 100, already in use by the group: users - continuing as force_gid variable has been set. Group name to use: users
Enter iCloud password for XXX@hotmail.com: 
Bad username or password for XXX@hotmail.com
Enter iCloud password for XXX@hotmail.com: 
Bad username or password for XXX@hotmail.com
Enter iCloud password for XXX@hotmail.com: 
```

**Comment by dlang123** [comment]
Adding here.. I have two installs of the docker pointing to two totally different configurations.

I set up mine without issue initially.  I setup the 2nd one without issue. When the first container restarted due to a config change by me, it refused to connect with an authentication error.

I deleted my original install and config folders to start fresh, and continue to receive this error.  I have verified web access from different browsers without issue so the passwords are good and I have access to photos.  The 2nd container is still running without issues and downloading pics every day.

**Comment by etoNcYCer** [comment]
> Adding here.. I have two installs of the docker pointing to two totally different configurations.
> 
> I set up mine without issue initially. I setup the 2nd one without issue. When the first container restarted due to a config change by me, it refused to connect with an authentication error.
> 
> I deleted my original install and config folders to start fresh, and continue to receive this error. I have verified web access from different browsers without issue so the passwords are good and I have access to photos. The 2nd container is still running without issues and downloading pics every day.

I just started having the same problem this morning.

**Comment by Soulplayer** [comment]
same error. Both my containers are down.

**Comment by dlang123** [comment]
Problem with icloudpd and not the docker container for Unraid.

https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/729

**Comment by imzenreally** [comment]
@dlang123 the unraid template is still pointing at boredazfuck's image - and not the iCloud-photos-downloader - I've been following the thread on the iCloud Photos downloader - looks like they've released a fix - do we need to point the template to that docker image instead of boredazfucks? looks like he hasn't built a new image in that repo in a while

**Comment by dlang123** [comment]
> @dlang123 the unraid template is still pointing at boredazfuck's image - and not the iCloud-photos-downloader - I've been following the thread on the iCloud Photos downloader - looks like they've released a fix - do we need to point the template to that docker image instead of boredazfucks? looks like he hasn't built a new image in that repo in a while

The newest prebuilt docker on docker hub is 6 days ago, so I would wait for them to push the newest docker up since it has only been somewhat fixed in the last day or two.  I need to go learn how to build the unraid templates, I have some other projects I have pushed pull requests to, but they seem to have died.

**Comment by imzenreally** [comment]
> > @dlang123 the unraid template is still pointing at boredazfuck's image - and not the iCloud-photos-downloader - I've been following the thread on the iCloud Photos downloader - looks like they've released a fix - do we need to point the template to that docker image instead of boredazfucks? looks like he hasn't built a new image in that repo in a while
> 
> 
> 
> The newest prebuilt docker on docker hub is 6 days ago, so I would wait for them to push the newest docker up since it has only been somewhat fixed in the last day or two.  I need to go learn how to build the unraid templates, I have some other projects I have pushed pull requests to, but they seem to have died.

Looks like boredazfcukis still updating dockerhub I was only looking at the GitHub page which hasn't had a commit in like two years (or so I thought I read earlier today) regardless I think it's a moot point looks like @boredazfcuk is still maintaining this
